import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/Navigation";
import { supabase } from "@/lib/supabse";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`min-h-dvh grid grid-cols-[1fr] grid-rows-[auto_1fr] ${poppins.className}`}
      >
        <Navigation />
        <main className="bg-base-200">{children}</main>
      </body>
    </html>
  );
}
